name: Tarefas Ebac

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Send Mail
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ github.workflow }} - ${{ github.job }} has ${{ job.status }}
          body: |
            ${{ github.actor }} created commit:

            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}

            Job: ${{ github.job }}
            
            Worflow: ${{ github.workflow }}

            Workflow Status: ${{ job.status }}

            See changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
          to: saynarah.nabuco@gmail.com
          from: GitHub Actions Notifications
