name: Send Email on Commit

on: 
  push: 
    branches:
      - main  # Replace with the branch you want to monitor (e.g., master)

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Send email notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.SMTP_SERVER }}
        server_port: ${{ secrets.SMTP_PORT }}
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        from: ${{ secrets.EMAIL_USERNAME }}
        to: 'saynarah.nabuco@gmail.com'
        subject: 'New Commit Notification on GitHub'
        body: |
          A new commit was made in your repository.
          Commit message: ${{ github.event.head_commit.message }}
          Commit by: ${{ github.event.head_commit.author.name }}
        
        
